### ISSUE TITLE
Typo in repo name?

### ISSUE THREAD

**Issue by hjacobs** [zalando/nakadi-klients#4]
Shouldn't it be "clients"?

**Comment by valgog** [comment]
But it makes it more German 😁

**Comment by hjacobs** [comment]
@valgog let's rename to "nakadi-klienten" :laughing:

**Comment by codechimp** [comment]
actually, it is supposed to be derived from gregorian because nakadi is a gregorian name as well :-). however, valentine already told me that it should be klienti in this case....damn google translator ;-)
