### ISSUE TITLE
newest_available_offset

### ISSUE THREAD

**Issue by DaKine23** [zalando/nakadi-klients#42]
Java Client

If i try to get the newestAvailableOffset from partitions following exception occurs

{"timestamp":1464166478109,"status":500,"error":"Internal Server Error","exception":"com.fasterxml.jackson.databind.JsonMappingException","message":"No suitable constructor found for type [simple type, class org.zalando.nakadi.client.java.model.Partition]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)\n at [Source: [{\"oldest_available_offset\":\"0\",\"newest_available_offset\":\"26\",\"partition\":\"0\"}]; line: 1, column: 3] (through reference chain: java.util.ArrayList[0])","path":"/subscription"}

**Comment by kanuku** [comment]
Already fixed!
