### ISSUE TITLE
validation_strategies field not recognized by Nakadi while creating event type (latest version)

### ISSUE THREAD

**Issue by ignacio-ifm** [zalando/nakadi-klients#43]
I get:

`ClientHandlerImpl-95 [] WARN ForkJoinPool-2-worker-5: http-stats(400) - {"type":"http://httpstatus.es/400","title":"Bad Request","status":400,"detail":"Unrecognized field \"validation_strategies\" (class de.zalando.aruha.nakadi.domain.EventType), not marked as ignorable (8 known properties: \"schema\", \"default_statistic\", \"partition_strategy\", \"name\", \"owning_application\", \"category\", \"enrichment_strategies\", \"partition_key_fields\"])\n at [Source: java.io.PushbackInputStream@46864fb8; line: 1, column: 100] (through reference chain: de.zalando.aruha.nakadi.domain.EventType[\"validation_strategies\"])"} - problem: The request contains bad syntax or cannot be fulfilled. `

while calling .createEventType(eventTypeCreaton) to the latest development version of Nakadi.

**Comment by kanuku** [comment]
#41
