### ISSUE TITLE
Maven Import

### ISSUE THREAD

**Issue by DaKine23** [zalando/nakadi-klients#47]
<dependency>
    <groupId>org.zalando.laas</groupId>
    <artifactId>nakadi-clients</artifactId>
    <version>2.0-SNAPSHOT</version>
  </dependency>

should be changed to

  <dependency>
    <groupId>org.zalando.laas</groupId>
    <artifactId>nakadi-clients</artifactId>
    <version>2.0.0-pre-alpha</version>
  </dependency>

**Comment by kanuku** [comment]
Done!
