### ISSUE TITLE
Test libraries with compile scope

### ISSUE THREAD

**Issue by ignacio-ifm** [zalando/nakadi-klients#48]
[INFO] |  +- junit:junit:jar:javadoc:4.12:compile
[INFO] |  +- junit:junit:jar:sources:4.12:compile
[INFO] |  +- org.mockito:mockito-core:jar:javadoc:1.10.19:compile
[INFO] |  \- org.mockito:mockito-core:jar:sources:1.10.19:compile

The client has those dependencies in compile scope, so they leak when used. Test scope would fix it.

**Comment by kanuku** [comment]
Remove withsources() from dependency notation.
Related to a bug in [sbt](https://github.com/sbt/sbt/issues/2001).
