### ISSUE TITLE
client.listenForEvents does not ends

### ISSUE THREAD

**Issue by OakimUa** [zalando/nakadi-klients#7]
client.listenForEvents does not ends because it do not receive EOL
when I listening only for existing events

**Comment by OakimUa** [comment]
Actually, it receives EOL after cursor inside simple stream event and cycling

**Comment by codechimp** [comment]
This is intended behaviour. The client keeps listening until the connection is closed. if the connecting is kept open, you might need to change your communication setting. EOL characters are ignored as it does not make sense to pass a partial response to the listeners
