### ISSUE TITLE
ClientBuilder's fluent API should support single statements

### ISSUE THREAD

**Issue by danielrohe** [zalando/nakadi-klients#83]
The ClientBuilder currently only supports chaining like

    new ClientBuilder().withHost(...).withPort(...)....buildClient();

It should also support

    ClientBuilder builder = new ClientBuilder();
    builder.withHost(...);
    builder.withPort(...);
    builder.buildClient();

to create a client.

**Comment by kanuku** [comment]
We like to keep the builders immutable, you will be able to achieve it as following:
```java
		ClientBuilder builder = new ClientBuilder();
		builder=builder.withHost("");
		builder=builder.withPort(443);
		Client client2=builder.buildJavaClient();
```
